Add support for OpenMW
cobalt2727/L4T-Megascript pull request #109
Opened 2022-07-13 03:27 UTC by EyeCantCU

Currently, the PPA for OpenMW is broken on Bionic for aarch64 so we need to build OpenMW and OpenMW's implementation of OpenSceneGraph from source on 18.04.

On later versions of Ubuntu, simply add the PPA and proceed with installation as usual.

2022-07-13 20:19 UTC, cobalt2727 requested changes

2022-07-13 21:06 UTC, EyeCantCU commented on scripts/games_and_emulators/openmw.sh
> +get_system || error_user "Failed to scan your system for specs - run this script via the Megascript or the helper script!"
Good point. I'll change it to a standard error and remove the bit about the megascript

2022-07-13 21:06 UTC, EyeCantCU commented on scripts/games_and_emulators/openmw.sh
> +else
All right

2022-07-13 21:09 UTC, EyeCantCU commented on scripts/update.sh
> +        description="Do you want to update OpenMW? (May take 5 minutes to 3 hours)"
3 hours is an accurate gauge of the time on my Switch using standard clocks. It might be a good idea to remove it from the update script though as you're right - it doesn't update too frequently. I think I'll just remove it

2022-07-14 02:53 UTC, cobalt2727 requested changes
Sorry I keep nitpicking...

2022-07-14 02:53 UTC, cobalt2727 commented on scripts/games_and_emulators/openmw.sh
> +get_system || error "Failed to scan your sytem specs"
`error` is also actually a custom function of ours

2022-07-14 02:53 UTC, cobalt2727 commented on scripts/games_and_emulators/openmw.sh
> +  cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-march=native \
Considering you add and install a PPA for GCC 11, you should set up an if statement that runs a different `cmake ..` command on 18.04 systems that calls in the alternative compiler. Check Dolphin's implementation for a reference.

2022-07-14 02:53 UTC, cobalt2727 commented on scripts/games_and_emulators/openmw.sh
> +  make -j$(($(nproc)-1)) || error "Compilation failed"
Oh, nice, did 3 cores instead of all 4 work without running out of memory for you?

2022-07-14 02:53 UTC, cobalt2727 commented on scripts/games_and_emulators/openmw.sh
> +  cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-march=native \
Same suggestion here as I made for openscenegraph - set up different `cmake ..` lines with different parameters depending on whether the user is building with 18.04 (and therefore the PPA's version of GCC) or not

2022-07-14 03:13 UTC, EyeCantCU commented on scripts/games_and_emulators/openmw.sh
> +get_system || error "Failed to scan your sytem specs"
Yes, I saw it. I figured we still need to point out that retrieving specifications failed

2022-07-14 03:20 UTC, EyeCantCU commented on scripts/games_and_emulators/openmw.sh
> +  cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-march=native \
The script only builds from source on 18.04 otherwise the script adds the existing OpenMW PPA and installs openmw that way since they only plan to drop support for bionic. I actually have 11 commented out until openmw-48 drops and actually needs it due to C++ 20 but I might as well just fully enable it now and adjust flags accordingly since we'll likely need it soon anyway

2022-07-14 03:21 UTC, EyeCantCU commented on scripts/games_and_emulators/openmw.sh
> +  make -j$(($(nproc)-1)) || error "Compilation failed"
Yes, it did! I tested it this morning :)

2022-07-14 03:21 UTC, EyeCantCU commented on scripts/games_and_emulators/openmw.sh
> +  cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-march=native \
https://github.com/cobalt2727/L4T-Megascript/pull/109#discussion_r920715282

2022-07-14 04:08 UTC, EyeCantCU commented
I want this script to be as complete as possible so nitpick away :)

2022-07-14 12:17 UTC, merged

2022-07-14 12:17 UTC, cobalt2727 commented
Thanks for setting this up!